# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtApp\ui/QtMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox_cam_left = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cam_left.setGeometry(QtCore.QRect(280, 240, 42, 22))
        self.spinBox_cam_left.setObjectName("spinBox_cam_left")
        self.spinBox_cam_right = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cam_right.setGeometry(QtCore.QRect(610, 240, 42, 22))
        self.spinBox_cam_right.setObjectName("spinBox_cam_right")
        self.cam_left = QtWidgets.QLabel(self.centralwidget)
        self.cam_left.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.cam_left.setAutoFillBackground(False)
        self.cam_left.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_left.setText("")
        self.cam_left.setScaledContents(True)
        self.cam_left.setObjectName("cam_left")
        self.cam_right = QtWidgets.QLabel(self.centralwidget)
        self.cam_right.setGeometry(QtCore.QRect(330, 0, 320, 240))
        self.cam_right.setAutoFillBackground(False)
        self.cam_right.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_right.setText("")
        self.cam_right.setScaledContents(True)
        self.cam_right.setObjectName("cam_right")
        self.cam_disparity = QtWidgets.QLabel(self.centralwidget)
        self.cam_disparity.setGeometry(QtCore.QRect(0, 280, 320, 240))
        self.cam_disparity.setAutoFillBackground(False)
        self.cam_disparity.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_disparity.setText("")
        self.cam_disparity.setScaledContents(True)
        self.cam_disparity.setObjectName("cam_disparity")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 231, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 202, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_available_cam_count = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_available_cam_count.setObjectName("label_available_cam_count")
        self.horizontalLayout.addWidget(self.label_available_cam_count)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 202, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_corner_X = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_corner_X.setProperty("value", 9)
        self.spinBox_corner_X.setObjectName("spinBox_corner_X")
        self.horizontalLayout_3.addWidget(self.spinBox_corner_X)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_corner_Y = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_corner_Y.setProperty("value", 6)
        self.spinBox_corner_Y.setObjectName("spinBox_corner_Y")
        self.horizontalLayout_3.addWidget(self.spinBox_corner_Y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.btn_callibration = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_callibration.setObjectName("btn_callibration")
        self.verticalLayout_2.addWidget(self.btn_callibration)
        self.verticalLayout.addWidget(self.groupBox)
        self.btn_stereoCallibration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_stereoCallibration.setObjectName("btn_stereoCallibration")
        self.verticalLayout.addWidget(self.btn_stereoCallibration)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RGB-D Detector"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Information"))
        self.label_2.setText(_translate("MainWindow", "Available Cam Count:"))
        self.label_available_cam_count.setText(_translate("MainWindow", "0"))
        self.groupBox.setTitle(_translate("MainWindow", "Callibration"))
        self.label_4.setText(_translate("MainWindow", "Corner X:"))
        self.label_5.setText(_translate("MainWindow", "Corner Y:"))
        self.btn_callibration.setText(_translate("MainWindow", "Callibration"))
        self.btn_stereoCallibration.setText(_translate("MainWindow", "Stereo Callibration"))

