# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './PDStereo\QtApp\ui/QtMain.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox_cam_left = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cam_left.setGeometry(QtCore.QRect(280, 240, 42, 22))
        self.spinBox_cam_left.setObjectName("spinBox_cam_left")
        self.spinBox_cam_right = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cam_right.setGeometry(QtCore.QRect(610, 240, 42, 22))
        self.spinBox_cam_right.setObjectName("spinBox_cam_right")
        self.cam_left = QtWidgets.QLabel(self.centralwidget)
        self.cam_left.setGeometry(QtCore.QRect(0, 0, 320, 240))
        self.cam_left.setAutoFillBackground(False)
        self.cam_left.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_left.setText("")
        self.cam_left.setScaledContents(True)
        self.cam_left.setObjectName("cam_left")
        self.cam_right = QtWidgets.QLabel(self.centralwidget)
        self.cam_right.setGeometry(QtCore.QRect(330, 0, 320, 240))
        self.cam_right.setAutoFillBackground(False)
        self.cam_right.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_right.setText("")
        self.cam_right.setScaledContents(True)
        self.cam_right.setObjectName("cam_right")
        self.cam_disparity = QtWidgets.QLabel(self.centralwidget)
        self.cam_disparity.setGeometry(QtCore.QRect(0, 280, 320, 240))
        self.cam_disparity.setAutoFillBackground(False)
        self.cam_disparity.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_disparity.setText("")
        self.cam_disparity.setScaledContents(True)
        self.cam_disparity.setObjectName("cam_disparity")
        self.cam_detect = QtWidgets.QLabel(self.centralwidget)
        self.cam_detect.setGeometry(QtCore.QRect(330, 280, 320, 240))
        self.cam_detect.setAutoFillBackground(False)
        self.cam_detect.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.cam_detect.setText("")
        self.cam_detect.setScaledContents(True)
        self.cam_detect.setObjectName("cam_detect")
        self.checkBox_saveImages = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_saveImages.setGeometry(QtCore.QRect(10, 530, 101, 16))
        self.checkBox_saveImages.setAutoExclusive(False)
        self.checkBox_saveImages.setTristate(False)
        self.checkBox_saveImages.setObjectName("checkBox_saveImages")
        self.checkBox_show_remap = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_show_remap.setGeometry(QtCore.QRect(10, 250, 171, 16))
        self.checkBox_show_remap.setObjectName("checkBox_show_remap")
        self.checkBox_save_detected_image = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_save_detected_image.setGeometry(QtCore.QRect(330, 530, 171, 16))
        self.checkBox_save_detected_image.setObjectName("checkBox_save_detected_image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(240, 38))
        self.dockWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dockWidget.setFloating(False)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 60, 221, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 202, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox_corner_X = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_corner_X.setProperty("value", 9)
        self.spinBox_corner_X.setObjectName("spinBox_corner_X")
        self.horizontalLayout_3.addWidget(self.spinBox_corner_X)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.spinBox_corner_Y = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinBox_corner_Y.setProperty("value", 6)
        self.spinBox_corner_Y.setObjectName("spinBox_corner_Y")
        self.horizontalLayout_3.addWidget(self.spinBox_corner_Y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.btn_calibration = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btn_calibration.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_calibration.setObjectName("btn_calibration")
        self.verticalLayout_2.addWidget(self.btn_calibration)
        self.layoutWidget = QtWidgets.QWidget(self.dockWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 221, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_available_cam_count = QtWidgets.QLabel(self.layoutWidget)
        self.label_available_cam_count.setObjectName("label_available_cam_count")
        self.horizontalLayout.addWidget(self.label_available_cam_count)
        self.btn_camcnt_refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_camcnt_refresh.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_camcnt_refresh.setObjectName("btn_camcnt_refresh")
        self.horizontalLayout.addWidget(self.btn_camcnt_refresh)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 221, 101))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 201, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_detect_rgb = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_detect_rgb.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_detect_rgb.setObjectName("btn_detect_rgb")
        self.horizontalLayout_2.addWidget(self.btn_detect_rgb)
        self.btn_detect_rgbd = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btn_detect_rgbd.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_detect_rgbd.setObjectName("btn_detect_rgbd")
        self.horizontalLayout_2.addWidget(self.btn_detect_rgbd)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.label_detecting = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_detecting.setObjectName("label_detecting")
        self.horizontalLayout_4.addWidget(self.label_detecting)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.btn_stereoCalibration = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_stereoCalibration.setGeometry(QtCore.QRect(10, 170, 221, 51))
        self.btn_stereoCalibration.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.btn_stereoCalibration.setObjectName("btn_stereoCalibration")
        self.groupBox_Colors = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_Colors.setGeometry(QtCore.QRect(10, 330, 221, 181))
        self.groupBox_Colors.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.groupBox_Colors.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_Colors.setObjectName("groupBox_Colors")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RGB-D Detector"))
        self.checkBox_saveImages.setText(_translate("MainWindow", "Save Images"))
        self.checkBox_show_remap.setText(_translate("MainWindow", "Show Remapped Images"))
        self.checkBox_save_detected_image.setText(_translate("MainWindow", "Save detected images"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Information"))
        self.groupBox.setTitle(_translate("MainWindow", "Callibration"))
        self.label_4.setText(_translate("MainWindow", "Corner X:"))
        self.label_5.setText(_translate("MainWindow", "Corner Y:"))
        self.btn_calibration.setText(_translate("MainWindow", "Calibration"))
        self.label_2.setText(_translate("MainWindow", "Available Cam Count:"))
        self.label_available_cam_count.setText(_translate("MainWindow", "0"))
        self.btn_camcnt_refresh.setText(_translate("MainWindow", "Refresh"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Detecting"))
        self.btn_detect_rgb.setText(_translate("MainWindow", "RGB"))
        self.btn_detect_rgbd.setText(_translate("MainWindow", "RGBD"))
        self.label.setText(_translate("MainWindow", "Target:"))
        self.label_detecting.setText(_translate("MainWindow", "None"))
        self.btn_stereoCalibration.setText(_translate("MainWindow", "Stereo Calibration"))
        self.groupBox_Colors.setTitle(_translate("MainWindow", "Colors"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

